Repository mohicans-pop-2008/vinto, pull requests merged in 2020-10, with the labels that each got.

#8 Addresses Iss#5
  package-lock.json
  package.json
  src/App.jsx
  src/components/sidebar/engagement.jsx
  src/index.jsx
  src/store/engagementScore.js
  src/store/index.js
Labels: enhancement

#12 Actually address Iss#4
  package-lock.json
  package.json
  src/App.jsx
  src/components/conference/video.jsx
  src/store/index.js
  src/store/participants.js
  test/simple_test.js
  utils/jitsi.config.js
Labels: enhancement

#15 dep: upgrade lib-jitsi-meet
  package.json
Labels: maintenance

#18 PULL REQUEST - Iss#13 - TO BE MERGED OCTOBER 15 AM
  package-lock.json
  package.json
  server/index.js
  server/socket/index.js
  src/App.jsx
  src/components/meetingControls/controls.jsx
  src/components/meetingControls/mute.jsx
  src/components/meetingControls/raiseHand.jsx
  src/components/sidebar/hands.jsx
  src/socket/index.js
  src/store/index.js
  src/store/raisedHands.js
Labels: enhancement

#48 Iss#45
  src/App.jsx
  src/components/conference/conference.jsx
  src/components/conference/conference.module.css
  src/components/conference/video.jsx
  src/components/conference/video.module.css
  src/uicontainers/UIGridLayout.jsx
  src/uicontainers/UIGridLayout.module.css
Labels: enhancement

#53 feat: makes Vinto respond to users leaving
  src/App.jsx
  utils/jitsiConnector.js
Labels: enhancement

#55 Likely resolves null-video Iss#52
  src/App.jsx
Labels: bug

#57 introduce layout algorithm : resolve issue 49
  src/components/conference/'
  src/components/conference/conference.jsx
  src/components/conference/conference.module.css
  src/components/conference/video.jsx
  src/components/conference/video.module.css
Labels: enhancement

#59 FEAT: Vinto users can mute and unmute their video. Remote participants pick up on this behavior as well.
  package-lock.json
  package.json
  src/App.jsx
  src/components/conference/video.jsx
  src/components/meetingControls/audioMute.jsx
  src/components/meetingControls/controls.jsx
  src/components/meetingControls/videoMute.jsx
  utils/jitsi.config.js
  utils/jitsiConnector.js
Labels: enhancement, help wanted

#63 Vinto users can now specify a room name
  .babelrc
  package-lock.json
  package.json
  src/App.jsx
  src/components/conference/'
  src/components/conference/conference.jsx
  src/components/joinForm.jsx
  webpack.config.js
Labels: enhancement

#66 Resolve layout algorithm i60
  src/App.jsx
  src/components/conference/conference.jsx
  src/components/conference/video.jsx
Labels: enhancement

#64 Style and layout added i58
  package-lock.json
  package.json
  src/App.jsx
  src/components/conference/conference.module.css
  src/components/joinForm.jsx
  src/components/meetingControls/audioMute.jsx
  src/components/meetingControls/controls.jsx
  src/components/meetingControls/emoji.jsx
  src/components/meetingControls/raiseHand.jsx
  src/components/meetingControls/screenShare.jsx
  src/components/meetingControls/videoMute.jsx
  src/components/sidebar/engagement.jsx
  src/components/sidebar/hands.jsx
  src/components/sidebar/sidebar.jsx
  src/components/style.jsx
Labels: enhancement

#69 Color the background of hands raised i58
  .gitignore
  package-lock.json
  package.json
  src/components/sidebar/hand.module.css
  src/components/sidebar/hands.jsx
  src/components/sidebar/sidebar.jsx
  src/components/style.jsx
Labels: enhancement

#74 Tweak layout to have fixed sidebar and control size - i58
  package-lock.json
  package.json
  public/index.html
  public/vinto-horizontal-logo.png
  public/vinto-vertical-logo.png
  src/App.css
  src/App.jsx
  src/components/conference/conference.module.css
  src/components/conference/video.module.css
  src/components/joinForm.jsx
  src/components/joinForm.module.css
  src/components/meetingControls/audioMute.jsx
  src/components/meetingControls/controls.jsx
  src/components/meetingControls/emoji.jsx
  src/components/meetingControls/leave.jsx
  src/components/meetingControls/leave.module.css
  src/components/meetingControls/raiseHand.jsx
  src/components/meetingControls/screenShare.jsx
  src/components/meetingControls/videoMute.jsx
  src/components/sidebar/hand.module.css
  src/components/sidebar/hands.jsx
  src/components/sidebar/handsModal.jsx
  src/components/style.jsx
  src/index.jsx
  src/store/index.js
  src/store/name.js
  src/uicontainers/UIGridLayout.module.css
Labels: enhancement
